<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>MyApp.UI</RootNamespace>
    <AssemblyName>myapp</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Bindable.fs" />
    <Compile Include="ViewModels.fs" />
    <Compile Include="Views/MainWindow.axaml.fs" />
    <Compile Include="Shell.fs" />
    <Compile Include="App.axaml.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="ShadUI" />
    <PackageReference Include="Elmish.Avalonia.Glue" />
    <PackageReference Include="Elmish.Avalonia.Glue.Projection" />
    <PackageReference Include="Axial" />
    <PackageReference Include="Axial.FileSystem" />
    <PackageReference Include="Axial.PlatformService" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyApp.Core\MyApp.Core.fsproj" />
  </ItemGroup>
</Project>
